name: Test and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest  # Windows環境を使用
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-timeout pytest-xvfb
    
    - name: Run tests
      run: |
        python -m pytest test_qr_scan.py -v --timeout=300
      env:
        PYTHONUNBUFFERED: 1
        DISPLAY: :99

  release:
    needs: test
    runs-on: windows-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get latest tag
      id: get_tag
      run: |
        $latest_tag = git describe --tags --abbrev=0
        echo "::set-output name=tag::$latest_tag"

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_tag.outputs.tag }}
        release_name: Release ${{ steps.get_tag.outputs.tag }}
        draft: false
        prerelease: false 