name: Test and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-timeout pytest-xvfb
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -m pytest test_qr_scan.py -v --timeout=300
      env:
        PYTHONUNBUFFERED: 1
        DISPLAY: :99

  release:
    needs: test
    runs-on: windows-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        body: |
          # QRコードスキャナーアプリケーション ${{ github.ref_name }}
          
          ## 変更内容
          - 初期リリース
          - QRコードのスキャン機能
          - QRコードの生成機能
          - テキスト入力の検証機能
          
          ## インストール方法
          ```bash
          pip install -r requirements.txt
          python qr_scan.py
          ``` 