name: Test and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-timeout pytest-xvfb
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -m pytest test_qr_scan.py -v --timeout=300
      env:
        PYTHONUNBUFFERED: 1
        DISPLAY: :99

  release:
    needs: test
    runs-on: windows-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get latest tag or create new one
      id: get_tag
      run: |
        try {
          $latest_tag = git describe --tags --abbrev=0
          echo "::set-output name=tag::$latest_tag"
          echo "::set-output name=is_new::false"
        } catch {
          # タグがない場合は新規作成
          $version = "v1.0.0"
          git tag $version
          git push origin $version
          echo "::set-output name=tag::$version"
          echo "::set-output name=is_new::true"
        }

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_tag.outputs.tag }}
        release_name: Release ${{ steps.get_tag.outputs.tag }}
        draft: false
        prerelease: false
        body: |
          # QRコードスキャナーアプリケーション ${{ steps.get_tag.outputs.tag }}
          
          ## 変更内容
          - 初期リリース
          - QRコードのスキャン機能
          - QRコードの生成機能
          - テキスト入力の検証機能
          
          ## インストール方法
          ```bash
          pip install -r requirements.txt
          python qr_scan.py
          ``` 